### PR TITLE
Added debug

### PR DESCRIPTION
**Pull request by paulomcnally**
Added debug.

Need implementation.

### CODE REVIEW

**Comment by superkhau** [comment]
Would you like to add more debug statements to the code itself? ie. stuff to actually print out like the other connectors?

**Comment by paulomcnally** [comment]
Yes, I will do it

**Comment by superkhau** [comment]
TY

**Comment by superkhau** [comment]
You still working on this?

**Comment by superkhau** [comment]
@paulomcnally If you're still interested in working on this, please submit another PR. Gonna close this as abandoned.

**Pull request closed without merging**
