### PR TITLE
Eslint in favour of jshint

### PR DESCRIPTION
**Pull request by superkhau**
Connect to https://github.com/strongloop/loopback-connector-redis/issues/26

### CODE REVIEW

**Comment by superkhau** [comment]
test please

**Comment by superkhau** [comment]
test please

**Comment by superkhau** [comment]
Waiting for @rmg to look into windows failures. Possibly related to https://github.com/npm/npm/issues/10826. Happens intermittently on node 4+6 on windows.

1st run -- node 4 + 6 on windows has the error
2nd run -- node 6 on windows has the error
3rd run -- node 4 on windows has the error

**Comment by superkhau** [comment]
@0candy PTAL

**Comment by rmg** [comment]
@slnode test please

**Comment by superkhau** [comment]
@0candy @rmg is working on this.

**Comment by superkhau** [comment]
test please

**Comment by superkhau** [comment]
@rmg Thanks for looking into the failure.

**Pull request merged**
