### PR TITLE
Feature/eslint

### PR DESCRIPTION
**Pull request by sqlwwx**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by superkhau** [comment]
Rejecting in favour of updated https://github.com/strongloop/loopback-connector-redis/pull/27

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
