### PR TITLE
Remove null objects returned from redis

### PR DESCRIPTION
**Pull request by behrad**
this fixes blown 'not found' default behavior for loopback-connector and so findOrCreate also works.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by superkhau** [comment]
Can you resolve the merge conflicts so I can test with our CI?

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by superkhau** [comment]
@behrad I'm closing this as abandoned as it's been more than year. Please send another PR if you are still keen to land this. Closing.

**Pull request closed without merging**
